---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:

    - name: 'be sure homebrew is updated'
      homebrew: update_homebrew=yes

    - include: tasks/brew-package.yml
    - include: tasks/brew-cask-package.yml

    - name: 'be sure gitsubmodule is initialized'
      command: git submodule update --init

    - name: 'be sure dotfiles is linked'
      file: src=~/dotfiles/dotfiles/{{ item.name }} dest=~/{{ item.dest_name if item.dest_name is defined else item.name }} state=link force=yes
      with_items:
        - { name: '.vimrc' }
        - { name: '.vim' }
        - { name: '.tmux.conf' }
        - { name: '.tmux' }
        - { name: '.screenrc' }
        - { name: '.zshrc' }
        - { name: 'platforms/macosx/.zshenv', dest_name: '.zshenv' }
        - { name: 'platforms/macosx/.zshrc.platforms', dest_name: '.zshrc.platforms' }

#    - name: 'be sure vim plugins are installed'
#      shell: vim +NeoBundleInstall +qall



